### ISSUE TITLE
Error Provisioning

### ISSUE THREAD

**Issue by gparrar** [silinternational/vagrant-boot2docker#2]
Hello Guys, I'm trying to setup your image and create an environment for myself but I'm getting trouble building the image for the first time.

I get the following error when I do vagrant up

==> default: Attempting graceful shutdown of VM...
==> default: Checking if box 'AlbanMontaigu/boot2docker' is up to date...
==> default: Clearing any previously set forwarded ports...
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
    default: Adapter 2: hostonly
==> default: Forwarding ports...
    default: 2375 => 2375 (adapter 1)
    default: 2376 => 2376 (adapter 1)
    default: 22 => 2222 (adapter 1)
==> default: Running 'pre-boot' VM customizations...
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: docker
    default: SSH auth method: password
    default: Warning: Connection timeout. Retrying...
    default: Warning: Remote connection disconnect. Retrying...
==> default: Machine booted and ready!
==> default: Checking for guest additions in VM...
==> default: Configuring and enabling network interfaces...
==> default: Mounting shared folders...
    default: /vagrant => /Users/gp-work/workspace/mamuut/platform
    default: /workspace => /Users/gp-work/workspace/mamuut/platform/workspace
    default: /preload-images => /Users/gp-work/workspace/mamuut/platform/resources/docker-images
==> default: Machine already provisioned. Run `vagrant provision` or use the `--provision`
==> default: flag to force provisioning. Provisioners marked to run always will still run.
==> default: Running provisioner: recompose (shell)...
    default: Running: inline script
==> default: libffi.tcz: OK
==> default: expat2.tcz: OK
==> default: ncurses.tcz: OK
==> default: readline.tcz: OK
==> default: gdbm.tcz: OK
==> default: tcl.tcz: OK
==> default: tk.tcz: OK
==> default: ln: /etc/ssl: File exists
==> default: openssl.tcz: OK
==> default: bzip2-lib.tcz: OK
==> default: sqlite3.tcz: OK
==> default: python.tcz: OK
==> default: Running get-pip.py
==> default: Traceback (most recent call last):
==> default:   File "./get-pip.py", line 17759, in <module>
==> default:     
==> default: main()
==> default:   File "./get-pip.py", line 162, in main
==> default:     
==> default: bootstrap(tmpdir=tmpdir)
==> default:   File "./get-pip.py", line 82, in bootstrap
==> default:     
==> default: import pip
==> default:   File "/tmp/tmpWFYULz/pip.zip/pip/__init__.py", line 15, in <module>
==> default:   File "/tmp/tmpWFYULz/pip.zip/pip/vcs/subversion.py", line 9, in <module>
==> default:   File "/tmp/tmpWFYULz/pip.zip/pip/index.py", line 30, in <module>
==> default:   File "/tmp/tmpWFYULz/pip.zip/pip/wheel.py", line 35, in <module>
==> default:   File "/tmp/tmpWFYULz/pip.zip/pip/_vendor/distlib/scripts.py", line 14, in <module>
==> default:   File "/tmp/tmpWFYULz/pip.zip/pip/_vendor/distlib/compat.py", line 31, in <module>
==> default: ImportError
==> default: : 
==> default: cannot import name HTTPSHandler
==> default: /tmp/vagrant-shell: 
==> default: line 11: 
==> default: pip: not found
==> default: Preloading the docker-daemon with images
==> default: Get http:///var/run/docker.sock/v1.20/images/json: dial unix /var/run/docker.sock: no such file or directory.
==> default: * Are you trying to connect to a TLS-enabled daemon without TLS?
==> default: * Is your docker daemon up and running?
==> default: Traceback (most recent call last):
==> default:   File "/usr/local/bin/docker-compose", line 7, in <module>
==> default:     
==> default: from compose.cli.main import main
==> default: ImportError
==> default: : 
==> default: No module named compose.cli.main
==> default: Adding images in /preload-images.
==> default: Get http:///var/run/docker.sock/v1.20/containers/json: dial unix /var/run/docker.sock: no such file or directory.
==> default: * Are you trying to connect to a TLS-enabled daemon without TLS?
==> default: * Is your docker daemon up and running?
==> default: Get http:///var/run/docker.sock/v1.20/images/json: dial unix /var/run/docker.sock: no such file or directory.
==> default: * Are you trying to connect to a TLS-enabled daemon without TLS?
==> default: * Is your docker daemon up and running?
==> default:  
==> default: To connect to docker running on the Vagrant Box,
==> default: set your DOCKER_HOST ENV variable, one of:
==> default:  
==> default:   export DOCKER_HOST=tcp://10.0.2.15:2375
==> default:   export DOCKER_HOST=tcp://192.168.70.249:2375
==> default:  
==> default: Or, just use 'vagrant ssh' to connect, and run commands
==> default: from inside the box, e.g.:
==> default:  
==> default:   vagrant ssh
==> default:   cd /vagrant
==> default:   docker-compose ps
==> default:   docker images

Can somebody help me please?

**Comment by pkchesterton** [comment]
For some reason pip is not installing, which in turns preventing docker-compose from installing either. Without docker-compose, the default docker images are not started (although I'm pretty sure that docker itself is running, so you could have run 'vagrant ssh' and set up things manually).

In any case, the issue appears to be fixed in version 1.8.2 of the AlbanMontaigu/boot2docker vagrant box, so I've updated this Vagrantfile to use that version.

**Comment by fillup** [comment]
@gparrar - @pkchesterton updated the boot2docker image to 1.8.2 which resolved the pip issue, but we also just updated it to not need pip for installing docker-compose anyway, so you should be good to go now if you pull the updates.
